Lection01 task02
js-tasks-ru/htmlcss-20220317_konstantin-cherepanov pull request #4
Opened 2022-03-27 12:06 UTC by CCher

2022-03-27 12:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-27 12:26 UTC, GSemikozov requested changes

2022-03-27 12:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@font-face {
стили нужно подключать не в компонентах, а на глобальном уровне, в файле .fonts.css

2022-03-27 12:26 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion-item" open>
все айтемы надо завернуть в div с классом блока (.accordion) - элементы блока не могут существовать вне блока

2022-03-27 12:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-item {
если блок - .accordion, то айтем - .accordion__item

2022-03-27 12:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-item .accordion-item__accordion-item-title::-webkit-details-marker {
.accordion-item__accordion-item-title -> .accordion-item__title

2022-03-27 12:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-item__accordion-item-text {
.accordion-item__accordion-item-text -> .accordion-item__text

2022-03-27 16:35 UTC, CCher commented on 03-lection1/02-accordion/accordion.css
> +@font-face {
да, я это понимаю. Сделал это как временное решение, т.к. задача стояла на уровне локального компонента.

2022-03-27 16:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-28 10:21 UTC, GSemikozov approved these changes

2022-03-28 10:21 UTC, merged