add solution for 04-lection2 02-task
js-tasks-ru/htmlcss-20220317_konstantin-cherepanov pull request #5
Opened 2022-04-02 12:59 UTC by CCher

2022-04-02 12:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-03 17:37 UTC, GSemikozov requested changes

2022-04-03 17:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
ширину и высоту блока не стоит фиксировать - сразу уменьшает возможность его переиспользования в других местах

2022-04-03 17:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title {
.skeleton__title и .skeleton__line - одно и то же. Модификаторы по типу .skeleton__title_line1 очень не информативны) лучше группировать по тому, что действительно меняется (ширина), например .skeleton__line_short

2022-04-03 17:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину лучше задавать в процентах

2022-04-04 18:09 UTC, GSemikozov approved these changes

2022-04-04 18:09 UTC, merged